name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  BUILD_ID: ${{ github.run_number }}
  DOCKER_REPO: yujungk1023/testwebapp
  STAGING_HOST: 210.109.83.250

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Git Checkout
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Maven Build
      - name: Build with Maven
        run: |
          chmod u+x mvnw
          ./mvnw clean package -Dmaven.test.skip=true

      # 4. Docker Login
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Docker Build & Push
      - name: Build & Push Docker Image
        run: |
          TODAY=$(date +%Y%m%d)
          DOCKER_TAG=${TODAY}_${BUILD_ID}
          IMAGE=${DOCKER_REPO}:${DOCKER_TAG}
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build --build-arg VERSION=$DOCKER_TAG -t $IMAGE -f Dockerfile .
          docker push $IMAGE

      # 6. Deploy to Staging via SSH
      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ env.STAGING_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker container rm -f stswebjpa || true
            docker container run -d \
              -p 80:8080 \
              -v /home/ubuntu/upload:/app/upload \
              --name=stswebjpa \
              ${{ env.IMAGE }}
